---
permalink: rhel-install/reference-system-requirements-for-oncommand-workflow-automation-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, system, requirements, install, hardware, requirements, install, wfa 
summary: 'WFA를 설치하기 전에 WFA(OnCommand Workflow Automation) 하드웨어 및 소프트웨어 요구 사항을 숙지해야 합니다.' 
---
= OnCommand Workflow Automation 설치를 위한 시스템 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA를 설치하기 전에 WFA(OnCommand Workflow Automation) 하드웨어 및 소프트웨어 요구 사항을 숙지해야 합니다.



== WFA 설치를 위한 하드웨어 요구사항

다음 표에는 WFA 서버의 최소 하드웨어 요구사항 및 권장 하드웨어 사양이 나와 있습니다.

[cols="3*"]
|===
| 구성 요소 | 최소 요구 사항 | 권장 사양 


 a| 
CPU
 a| 
2.27GHz 이상, 2코어, 64비트
 a| 
2.27GHz 이상, 2코어, 64비트



 a| 
RAM
 a| 
4GB
 a| 
8GB



 a| 
사용 가능한 디스크 공간
 a| 
5GB
 a| 
20GB

|===
[NOTE]
====
가상 머신(VM)에 WFA를 설치하는 경우 필요한 메모리와 CPU를 예약하여 VM에 충분한 리소스가 있어야 합니다. 설치 프로그램이 CPU 속도를 확인하지 않습니다.

====


== WFA 설치를 위한 소프트웨어 요구사항

다음 표에는 WFA 서버와 호환되는 모든 운영 체제 버전이 나와 있습니다.

[cols="2*"]
|===
| 운영 체제 | 버전 


 a| 
Red Hat Enterprise Linux
 a| 
6.5, 7.0, 7.1 64비트 운영 체제, 7.2, 7.3 및 7.4



 a| 
CentOS
 a| 
7.1, 7.2 및 7.3

|===
[NOTE]
====
WFA는 전용 물리적 시스템 또는 VM에 설치해야 합니다. WFA를 실행하는 서버에 다른 애플리케이션을 설치해서는 안 됩니다.

====


== 기타 최소 필수 소프트웨어

* 다음 브라우저 중 하나:
+
** Mozilla Firefox
** Microsoft Internet Explorer를 참조하십시오
** Google Chrome


* 브라우저에 맞는 최신 버전의 Adobe Flash Player
* Perl v5.10.1
+
'./WFA-version_number.bin -l' 명령을 사용하여 설치해야 하는 Perl 모듈에 대한 정보를 얻을 수 있습니다.



자세한 내용은 상호 운용성 매트릭스 툴을 참조하십시오.

* 관련 정보 *

http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]
