---
settings:
  name: OnCommand Workflow Automation 5.0
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: OnCommand Workflow Automation 5.0 문서
    url: "/index.html"
  - title: 릴리즈 노트
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: help
  - section: workflows
  - title: 법적 고지
    url: "/legal-notices.html"
