---
permalink: windows-install/task-back-up-oncommand-workflow-automation-using-powershell-script.html 
sidebar: sidebar 
keywords: back up, wfa, database, powershell, script 
summary: 'WFA(OnCommand Workflow Automation) 데이터베이스를 자주 백업하려는 경우 WFA 설치 패키지에 제공되는 PowerShell 스크립트를 사용할 수 있습니다.' 
---
= PowerShell 스크립트를 사용하여 WFA 데이터베이스를 백업합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation) 데이터베이스를 자주 백업하려는 경우 WFA 설치 패키지에 제공되는 PowerShell 스크립트를 사용할 수 있습니다.

.필요한 것
관리자 사용자 자격 증명, 설계자 자격 증명 또는 백업 사용자 자격 증명이 있어야 합니다.

.이 작업에 대해
자세한 내용은 REST 설명서를 참조하십시오.

. Windows PowerShell을 admin 사용자로 열고 WFA 데이터베이스를 백업합니다.
+
'<WFA_INSTALL_LOCATION\WFA\BIN\Backup.PS1> - User user_name - Password password - Path backup_file_path'

+
** WFA_INSTALL_LOCATION은 WFA 설치 디렉토리입니다.
** _user_name_은 admin 사용자, 설계자 또는 백업 사용자의 사용자 이름입니다.
** _password_는 admin 사용자, 설계자 또는 백업 사용자의 암호입니다.
** backup_file_path는 백업 파일의 전체 디렉토리 경로입니다.
+

NOTE: 백업 파일은 + "WFA_BACKUP_servername_.zip" 형식의 이름을 가진 zip 파일입니다

** WFA_BACKUP_ 은 파일 이름의 고정된 부분으로, 백업 서버의 이름입니다.
** '서버 이름'은 Windows 서버 환경에서 추출됩니다.
** 파일 이름의 고정 부분은 _.zip입니다. + * 예 * + 'C:\Program Files\NetApp\WFA\bin\Backup.ps1 - 사용자 백업 - 암호 MyPassword123 - 경로 C:\WFA_backups\backup_10_08_12'입니다
+
백업이 완료되면 'C:\WFA_Backups\backup_10__08_12\WFA_backup_myserver_.zip'이라는 출력이 표시됩니다



. * 선택 사항: * 백업 파일이 지정된 위치에 생성되었는지 확인합니다.

