---
permalink: windows-install/task-install-workflow-automation-on-windows.html 
sidebar: sidebar 
keywords: oncommand workflow automation, install, windows 
summary: 'WFA(OnCommand Workflow Automation)를 설치하여 스토리지 워크플로우를 생성한 후 사용자 지정하여 해당 환경에서 수행되는 스토리지 작업을 자동화할 수 있습니다.' 
---
= Windows에 OnCommand Workflow Automation를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation)를 설치하여 스토리지 워크플로우를 생성한 후 사용자 지정하여 해당 환경에서 수행되는 스토리지 작업을 자동화할 수 있습니다.

.필요한 것
* 설치 필수 구성 요소를 검토해야 합니다.
+
xref:reference-prerequisites-for-installing-workflow-automation.adoc[Workflow Automation 설치를 위한 사전 요구사항]

* WFA가 이전에 설치된 후 제거된 시스템에 WFA를 설치하는 경우 해당 시스템에 WFA 서비스가 없는지 확인해야 합니다.
* NetApp Support 사이트에서 WFA 설치 프로그램을 다운로드해야 합니다.
* Java의 자동 업그레이드 기능을 비활성화해야 합니다.


.이 작업에 대해
* 가상 머신(VM)에 WFA를 설치하는 경우 VM의 이름에 밑줄(_) 문자를 포함할 수 없습니다.
* WFA를 설치하기 전에 ActiveState ActivePerl이 설치됩니다.
+
이 설치는 WFA 서버에 설치된 ActivePerl의 다른 인스턴스에 영향을 주지 않습니다.

* WFA 4.2 이상을 다시 설치하기 전에 MySQL을 제거한 경우 MySQL 데이터 디렉터리를 삭제해야 합니다.
* MySQL을 직접 설치하는 경우, MySQL my.ini` 파일의 'Secure-File-Privilege'와 'QL-mode' 속성이 공백으로 설정됩니다.


.단계
. 관리자 권한이 있는 계정을 사용하여 Windows에 로그인합니다.
. Windows 탐색기를 열고 설치 파일이 있는 디렉터리로 이동합니다.
. WFA 설치:
+
** 대화형 설치
+
... 관리자 권한으로 WFA 설치 관리자 실행 파일('.exe')을 마우스 오른쪽 버튼으로 클릭하고 실행합니다.
... 다음 * 을 클릭합니다.
... 기본 admin 사용자의 자격 증명을 입력한 후 * Next * 를 클릭합니다.
+
기본 admin 암호는 다음 조건을 충족해야 합니다.

+
**** 최소 6자
**** 대문자 1개
**** 소문자 1개
**** 숫자 1개
**** 하나의 특수 문자 * 참고: * admin 사용자의 자격 증명을 기록해야 합니다.


... WFA 구성에 사용할 포트를 선택한 후 * 다음 * 을 클릭합니다.
... 사이트 이름과 회사 이름을 입력한 후 * 다음 * 을 클릭합니다.
+
사이트 이름에는 WFA 설치 위치(예: Pittsburgh, PA)가 포함될 수 있습니다.

... 기본 설치 위치를 변경하려면 WFA를 설치할 위치를 선택한 후 * 다음 * 을 클릭합니다.
... WFA 데이터베이스의 기본 위치를 변경하지 않으려면 * 다음 * 을 클릭합니다.
... 설치를 계속하려면 * 설치 * 를 클릭하십시오.
... 설치를 완료하려면 * 마침 * 을 클릭합니다.
... 다음 작업 중 하나를 선택하여 WFA가 성공적으로 설치되었는지 확인합니다.
+
**** 웹 브라우저를 통해 WFA에 액세스합니다.
**** Windows 서비스 콘솔을 사용하여 NetApp WFA Server 서비스와 NetApp WFA 데이터베이스 서비스가 실행 중인지 확인합니다.




** 자동 설치(명령 프롬프트에 있음): + "WFA-version_number-build_number.exe /s /v" WFA_admin_username=WFA_username WFA_admin_password=password WFA_admin_confirm_password=confirm admin 암호/WFA_mysql_pass=password mysql password WFA_mysql_mysql_install_site=site=site WFA_name WFA_HTTP_port.vtl_tv_port
+
* 예 *

+
'WFA-x64-v4.2.0.0.0-B2973881.exe /s/v" WFA_admin_username=admin WFA_admin_password=Company * 234 WFA_admin_confirm_password=Company * 234 WFA_mysql_mysql_pass=mysql * 234 WFA_install_site=nb_install_site=NetApp WFA_HTTP_port=9090_WFA_HTTPS_DATASDIR_ATASIr.Program=A432\EQR_AQR_STEDIR_EMORF=Company=Company=Company=Company=Company=Company=Company * 234 WFA_MASDIR_A432_Mscr_MASDIR_Mscr_MASDIR_Mscorm_MASYST

+

NOTE: '/qn' 옵션은 WFA에서 지원되지 않습니다.

+
명령 매개변수는 다음과 같습니다.

+
[cols="2*"]
|===
| 매개 변수 | 설명 


 a| 
_WFA_admin_사용자 이름_
 a| 
관리자 사용자 이름입니다

선택적 매개 변수입니다. 값을 지정하지 않으면 기본값 admin이 사용됩니다.



 a| 
_WFA_admin_password_
 a| 
관리자 암호입니다

필수 매개 변수입니다. 기본 admin 암호는 다음 조건을 충족해야 합니다.

*** 최소 6자
*** 대문자 1개
*** 소문자 1개
*** 숫자 1개
*** 특수 문자 1개




 a| 
_WFA_admin_confirm_password_
 a| 
관리자 암호입니다

필수 매개 변수입니다



 a| 
_WFA_MySQL_PASS_
 a| 
MySQL 사용자 암호입니다

필수 매개 변수입니다



 a| 
_CONFIRM_WFA_MySQL_PASS_
 a| 
MySQL 사용자 암호입니다

필수 매개 변수입니다



 a| 
_WFA_설치_사이트_
 a| 
WFA가 설치되어 있는 조직 구성 단위 필수 매개 변수



 a| 
_WFA_설치_조직 _
 a| 
WFA가 설치 중인 조직 또는 회사 이름입니다

필수 매개 변수입니다



 a| 
_WFA_HTTP_PORT_
 a| 
HTTP port 선택적 매개 변수입니다. 값을 지정하지 않으면 기본값 80이 사용됩니다.



 a| 
_WFA_HTTPS_포트_
 a| 
HTTPS 포트 선택적 매개 변수입니다. 값을 지정하지 않으면 기본값 443이 사용됩니다.



 a| 
_INSTALLDIR_
 a| 
설치 디렉토리 경로

선택적 매개 변수입니다. 값을 지정하지 않으면 기본 경로 ""C:\Program Files\NetApp\WFA\""가 사용됩니다.

|===




* 관련 정보 *

http://mysupport.netapp.com["NetApp 지원"]
